---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
spec:
  selector:
    matchLabels:
      application: taskmanager-provision
  replicas: 1 
  template:
    metadata:
      name: taskmanager-provision
      labels:
        application: taskmanager-provision
    spec:
      containers:
      - name: taskmanager-provision
        image: taskmanager
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-provision-nodeport
spec:
  selector:
    application: taskmanager-provision
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31001
  type: NodePort
---
