---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      application: frontend
  replicas: 1 
  template:
    metadata:
      name: frontend
      labels:
        application: frontend
    spec:
      containers:
      - name: frontend-taskmanager
        image: frontend-taskmanager
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  selector:
    application: frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31002
  type: NodePort
---
